# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

jms_serializer:
    metadata:
        directories:
            sylius-product:
                namespace_prefix: "Sylius\\Component\\Product"
                path: "@SyliusProductBundle/Resources/config/serializer"

doctrine:
    orm:
        dql:
            string_functions:
                JSONB_ARRAY_ELEMENTS_TEXT: Sylius\Bundle\ProductBundle\Doctrine\ORM\Query\AST\Function\JsonbArrayElementsText
