Sylius\Component\Product\Model\ProductAttribute:
    exclusion_policy: ALL
    xml_root_name: product-attribute
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
